import { IPO } from './types';

/**
 * Curated mainboard IPO board.
 *
 * Only mainboard issues are carried: the app deliberately leaves out SME issues (BSE SME /
 * NSE SME), which trade nothing like mainboard ones and were adding a second, noisier
 * category to every screen. The live merge drops anything upstream marks as SME too, so a
 * new SME opening can never reappear on the board.
 *
 * GMP, price bands, lot sizes, issue sizes, subscription and event dates below are
 * taken from public IPO trackers (IPO Ji's GMP board, live subscription report and
 * event calendar) and cross-checked against business press where the numbers moved.
 *
 * Snapshot: 14 September 2026, 2:15 PM IST.
 * Every row also carries its own `gmpUpdated` timestamp so the UI can show how fresh
 * that particular quote is instead of implying the whole board is live.
 *
 * Dates listed in `tentativeDates` are derived from the standard T+1 / T+2 working-day
 * cycle because no source has confirmed them yet - the UI marks them "(tentative)".
 */
export const DATA_AS_OF = '2026-09-14T14:15:00+05:30';
export const DATA_AS_OF_LABEL = '14 Sep 2026, 2:15 PM IST';
export const DATA_SOURCE_LABEL = 'IPO Ji (GMP board, live subscription & event calendar)';

const IPOT_RAW: IPO[] = [
  /* ---------------------------------------------------------------- open now */
  {
    id: 'veegaland-developers',
    name: 'Veegaland Developers',
    sector: 'Real Estate',
    segment: 'Mainboard',
    platform: 'NSE',
    openDate: '2026-09-10',
    closeDate: '2026-09-15',
    allotmentDate: '2026-09-16',
    listingDate: '2026-09-18',
    tentativeDates: [],
    priceBandLow: 130,
    priceBandHigh: 140,
    lotSize: 107,
    issueSizeCr: 210,
    issueType: 'Book built',
    exchanges: ['NSE', 'BSE'],
    gmp: 15,
    gmpUpdated: '2026-09-14T13:15:00+05:30',
    subscription: { qib: 0.49, nii: 1.01, retail: 1.78, total: 1.24, asOf: '11 Sep 2026, 5:06 PM' },
    about:
      'Kerala-based residential developer. ₹210 Cr issue with a minimum application of about ₹14,980 (107 shares) - the smallest retail outlay among the currently open mainboard issues.',
    sourceName: 'IPO Ji',
    sourceUrl: 'https://www.ipoji.com/ipo/veegaland-developers-ipo',
  },
  {
    id: 'manika-plastech',
    name: 'Manika Plastech',
    segment: 'Mainboard',
    platform: 'NSE',
    openDate: '2026-09-11',
    closeDate: '2026-09-16',
    allotmentDate: '2026-09-17',
    listingDate: '2026-09-19',
    tentativeDates: [],
    priceBandLow: 40,
    priceBandHigh: 43,
    lotSize: 348,
    issueSizeCr: 125.5,
    issueType: 'Book built',
    exchanges: ['NSE', 'BSE'],
    gmp: 9,
    gmpUpdated: '2026-09-14T14:15:00+05:30',
    subscription: { qib: 0.36, nii: 1.26, retail: 2.24, total: 1.49, asOf: '11 Sep 2026, 5:06 PM' },
    about:
      '₹125.5 Cr mainboard issue priced at ₹40-43. Retail portion led demand at 2.24x while QIBs were still filling up on day 1 of bidding.',
    sourceName: 'IPO Ji',
    sourceUrl: 'https://www.ipoji.com/ipo/manika-plastech-ipo',
  },
  {
    id: 'hero-motors',
    name: 'Hero Motors',
    sector: 'Auto & Mobility',
    segment: 'Mainboard',
    platform: 'NSE',
    openDate: '2026-09-16',
    closeDate: '2026-09-18',
    allotmentDate: '2026-09-21',
    listingDate: '2026-09-23',
    tentativeDates: [],
    priceBandLow: 79,
    priceBandHigh: 84,
    lotSize: 178,
    issueSizeCr: 1000,
    issueType: 'Book built',
    exchanges: ['NSE', 'BSE'],
    gmp: 17,
    gmpUpdated: '2026-09-14T12:30:00+05:30',
    about:
      '₹1,000 Cr mainboard issue from the Hero group mobility business, bidding 16-18 September. A minimum lot of 178 shares works out to about ₹14,952.',
    sourceName: 'IPO Ji',
    sourceUrl: 'https://www.ipoji.com/ipo/hero-motors-ipo',
  },
  {
    id: 'jindal-supreme',
    name: 'Jindal Supreme (India)',
    segment: 'Mainboard',
    platform: 'NSE',
    openDate: '2026-09-16',
    closeDate: '2026-09-18',
    allotmentDate: '2026-09-21',
    listingDate: '2026-09-23',
    tentativeDates: [],
    priceBandLow: 88,
    priceBandHigh: 93,
    lotSize: 161,
    issueSizeCr: 124.88,
    issueType: 'Book built',
    exchanges: ['NSE', 'BSE'],
    gmp: 17,
    gmpUpdated: '2026-09-14T12:30:00+05:30',
    about:
      '₹124.88 Cr mainboard issue at ₹88-93 a share, opening 16 September. One lot of 161 shares needs about ₹14,973.',
    sourceName: 'IPO Ji',
    sourceUrl: 'https://www.ipoji.com/ipo/jindal-supreme-ipo',
  },
  {
    id: 'ss-retail',
    name: 'SS Retail',
    segment: 'Mainboard',
    platform: 'NSE',
    openDate: '2026-09-16',
    closeDate: '2026-09-18',
    allotmentDate: '2026-09-21',
    listingDate: '2026-09-23',
    tentativeDates: [],
    priceBandLow: 403,
    priceBandHigh: 424,
    lotSize: 35,
    issueSizeCr: 500,
    issueType: 'Book built',
    exchanges: ['NSE', 'BSE'],
    gmp: 100,
    gmpUpdated: '2026-09-14T12:30:00+05:30',
    about:
      '₹500 Cr mainboard issue at ₹403-424 with the strongest grey market percentage among next week’s openings - about +24% at the last recorded quote.',
    sourceName: 'IPO Ji',
    sourceUrl: 'https://www.ipoji.com/ipo/ss-retail-ipo',
  },
  {
    id: 'nse',
    name: 'NSE (National Stock Exchange)',
    sector: 'Capital Markets',
    segment: 'Mainboard',
    platform: 'NSE',
    openDate: '2026-09-17',
    closeDate: '2026-09-21',
    allotmentDate: '2026-09-22',
    listingDate: '2026-09-24',
    tentativeDates: [],
    priceBandLow: 1700,
    priceBandHigh: 1785,
    lotSize: 8,
    issueSizeCr: 22561.57,
    issueType: 'Book built • 100% OFS (12.64 Cr shares)',
    exchanges: ['BSE'],
    gmp: 210,
    gmpUpdated: '2026-09-14T14:15:00+05:30',
    about:
      'The largest issue of the season: a ₹22,561.57 Cr offer for sale of 12.64 crore shares by existing NSE shareholders. One lot of 8 shares costs about ₹14,280. Shares will list on the BSE.',
    sourceName: 'IPO Ji / ET Now',
    sourceUrl: 'https://www.ipoji.com/ipo/nse-ipo',
  },
  {
    id: 'sonaselection-india',
    name: 'Sonaselection India',
    segment: 'Mainboard',
    platform: 'NSE',
    openDate: '2026-09-17',
    closeDate: '2026-09-21',
    allotmentDate: '2026-09-22',
    listingDate: '2026-09-24',
    tentativeDates: [],
    priceBandLow: 94,
    priceBandHigh: 99,
    lotSize: 150,
    issueSizeCr: 141.57,
    issueType: 'Book built',
    exchanges: ['NSE', 'BSE'],
    about:
      '₹141.57 Cr mainboard issue at ₹94-99 a share, bidding 17-21 September. No grey market quote recorded as of the last update.',
    sourceName: 'IPO Ji',
    sourceUrl: 'https://www.ipoji.com/ipo/sonaselection-india-ipo',
  },
  {
    id: 'a-one-steels',
    name: 'A-One Steels India',
    sector: 'Steel',
    segment: 'Mainboard',
    platform: 'NSE',
    openDate: '2026-09-24',
    closeDate: '2026-09-28',
    allotmentDate: '2026-09-29',
    listingDate: '2026-10-01',
    tentativeDates: ['open', 'close', 'allotment', 'listing'],
    issueSizeCr: 405,
    issueType: 'Book built',
    exchanges: ['NSE', 'BSE'],
    about:
      '₹405 Cr mainboard issue scheduled for 24-28 September. Price band, lot size and the post-bidding dates are yet to be confirmed.',
    sourceName: 'IPO Ji',
    sourceUrl: 'https://www.ipoji.com/ipo/a-one-steels-ipo',
  },

  /* ------------------------------------------- closed, awaiting allotment/listing */
  {
    id: 'pranav-constructions',
    name: 'Pranav Constructions',
    sector: 'Infrastructure',
    segment: 'Mainboard',
    platform: 'NSE',
    openDate: '2026-09-07',
    closeDate: '2026-09-09',
    allotmentDate: '2026-09-15',
    listingDate: '2026-09-16',
    tentativeDates: [],
    priceBandLow: 118,
    priceBandHigh: 124,
    lotSize: 120,
    issueSizeCr: 351.03,
    issueType: 'Book built',
    exchanges: ['NSE', 'BSE'],
    gmp: 44,
    gmpUpdated: '2026-09-14T12:30:00+05:30',
    subscription: { total: 126.34, asOf: 'Final' },
    about:
      '₹351.03 Cr civil construction issue that closed 9 September with the book subscribed 126.34x. Allotment is due 15 September and listing 16 September.',
    sourceName: 'IPO Ji',
    sourceUrl: 'https://www.ipoji.com/ipo/pranav-constructions-ipo',
  },
  {
    id: 'glass-wall-systems',
    name: 'Glass Wall Systems (India)',
    sector: 'Building Materials',
    segment: 'Mainboard',
    platform: 'NSE',
    openDate: '2026-09-08',
    closeDate: '2026-09-10',
    allotmentDate: '2026-09-11',
    listingDate: '2026-09-16',
    tentativeDates: ['allotment'],
    priceBandLow: 172,
    priceBandHigh: 182,
    lotSize: 82,
    issueSizeCr: 427.89,
    issueType: 'Book built',
    exchanges: ['NSE', 'BSE'],
    gmp: 50,
    gmpUpdated: '2026-09-14T12:30:00+05:30',
    subscription: { total: 81.65, asOf: 'Final' },
    about:
      '₹427.89 Cr architectural glazing and facade systems supplier. The book closed 81.65x subscribed and the shares are scheduled to list on 16 September.',
    sourceName: 'IPO Ji',
    sourceUrl: 'https://www.ipoji.com/ipo/glass-wall-systems-ipo',
  },
  {
    id: 'kanohar-electricals',
    name: 'Kanohar Electricals',
    sector: 'Power Equipment',
    segment: 'Mainboard',
    platform: 'NSE',
    openDate: '2026-09-08',
    closeDate: '2026-09-10',
    allotmentDate: '2026-09-11',
    listingDate: '2026-09-16',
    tentativeDates: ['allotment'],
    priceBandLow: 601,
    priceBandHigh: 632,
    lotSize: 23,
    issueSizeCr: 1055.74,
    issueType: 'Book built • Fresh + OFS',
    exchanges: ['NSE', 'BSE'],
    gmp: 238,
    gmpUpdated: '2026-09-14T14:15:00+05:30',
    subscription: { total: 90.59, asOf: 'Final' },
    about:
      '₹1,055.74 Cr transformer and EPC issue, 90.59x subscribed, listing 16 September. It carries the highest recorded premium on the board at +₹238 a share.',
    sourceName: 'IPO Ji',
    sourceUrl: 'https://www.ipoji.com/ipo/kanohar-electricals-ipo',
  },
  {
    id: 'prasol-chemicals',
    name: 'Prasol Chemicals',
    sector: 'Specialty Chemicals',
    segment: 'Mainboard',
    platform: 'NSE',
    openDate: '2026-09-08',
    closeDate: '2026-09-10',
    allotmentDate: '2026-09-11',
    listingDate: '2026-09-16',
    tentativeDates: ['allotment'],
    priceBandLow: 643,
    priceBandHigh: 676,
    lotSize: 22,
    issueSizeCr: 500,
    issueType: 'Book built',
    exchanges: ['NSE', 'BSE'],
    gmp: 0,
    gmpUpdated: '2026-09-14T08:45:00+05:30',
    subscription: { total: 3.47, asOf: 'Final' },
    about:
      '₹500 Cr specialty chemicals issue. The book closed 3.47x subscribed but the grey market quote has slipped to nil (trackers show anywhere between ₹0 and a small discount).',
    sourceName: 'IPO Ji',
    sourceUrl: 'https://www.ipoji.com/ipo/prasol-chemicals-ipo',
  },
  {
    id: 'asset-reconstruction',
    name: 'Asset Reconstruction Company (India)',
    sector: 'Financials',
    segment: 'Mainboard',
    platform: 'NSE',
    openDate: '2026-09-09',
    closeDate: '2026-09-11',
    allotmentDate: '2026-09-15',
    listingDate: '2026-09-17',
    tentativeDates: [],
    priceBandLow: 132,
    priceBandHigh: 139,
    lotSize: 107,
    issueSizeCr: 732.97,
    issueType: 'Book built • OFS',
    exchanges: ['NSE', 'BSE'],
    gmp: 15,
    gmpUpdated: '2026-09-14T12:30:00+05:30',
    subscription: { total: 20.1, asOf: 'Final' },
    about:
      '₹732.97 Cr offer for sale by the country’s oldest asset reconstruction company. The issue closed 20.10x subscribed; allotment 15 September, listing 17 September.',
    sourceName: 'IPO Ji',
    sourceUrl: 'https://www.ipoji.com/ipo/asset-reconstruction-ipo',
  },
  {
    id: 'rentomojo',
    name: 'Rentomojo',
    sector: 'Consumer Rentals',
    segment: 'Mainboard',
    platform: 'NSE',
    openDate: '2026-09-09',
    closeDate: '2026-09-11',
    allotmentDate: '2026-09-15',
    listingDate: '2026-09-17',
    tentativeDates: [],
    priceBandLow: 384,
    priceBandHigh: 404,
    lotSize: 37,
    issueSizeCr: 1255.57,
    issueType: 'Book built',
    exchanges: ['NSE', 'BSE'],
    gmp: 155,
    gmpUpdated: '2026-09-14T14:15:00+05:30',
    subscription: { total: 72.88, asOf: 'Final' },
    about:
      '₹1,255.57 Cr issue from the furniture and appliance rental marketplace. Closed 72.88x subscribed with the premium holding near +38%.',
    sourceName: 'IPO Ji',
    sourceUrl: 'https://www.ipoji.com/ipo/rentomojo-ipo',
  },
  {
    id: 'karamtara-engineering',
    name: 'Karamtara Engineering',
    sector: 'Solar & Transmission Structures',
    segment: 'Mainboard',
    platform: 'NSE',
    openDate: '2026-09-09',
    closeDate: '2026-09-11',
    allotmentDate: '2026-09-15',
    listingDate: '2026-09-17',
    tentativeDates: [],
    priceBandLow: 241,
    priceBandHigh: 254,
    lotSize: 59,
    issueSizeCr: 875,
    issueType: 'Book built',
    exchanges: ['NSE', 'BSE'],
    gmp: 68,
    gmpUpdated: '2026-09-14T12:30:00+05:30',
    subscription: { total: 66.01, asOf: 'Final' },
    about:
      '₹875 Cr issue from the solar module mounting structure and galvanised steel maker. Closed 66.01x subscribed, listing 17 September.',
    sourceName: 'IPO Ji',
    sourceUrl: 'https://www.ipoji.com/ipo/karamtara-engineering-ipo',
  },
  {
    id: 'lcc-projects',
    name: 'LCC Projects',
    sector: 'Civil Infrastructure',
    segment: 'Mainboard',
    platform: 'NSE',
    openDate: '2026-09-09',
    closeDate: '2026-09-11',
    allotmentDate: '2026-09-15',
    listingDate: '2026-09-17',
    tentativeDates: [],
    priceBandLow: 139,
    priceBandHigh: 146,
    lotSize: 102,
    issueSizeCr: 427.14,
    issueType: 'Book built',
    exchanges: ['NSE', 'BSE'],
    gmp: 59,
    gmpUpdated: '2026-09-14T12:30:00+05:30',
    subscription: { total: 49.57, asOf: 'Final' },
    about:
      '₹427.14 Cr civil works contractor, closed 49.57x subscribed. Trackers quote a premium of ₹59-61 a share, the highest percentage on the board at about +40%.',
    sourceName: 'IPO Ji',
    sourceUrl: 'https://www.ipoji.com/ipo/lcc-projects-ipo',
  },
  {
    id: 'manipal-payment',
    name: 'Manipal Payment & Identity Solutions',
    sector: 'Fintech & Payments',
    segment: 'Mainboard',
    platform: 'NSE',
    openDate: '2026-09-09',
    closeDate: '2026-09-11',
    allotmentDate: '2026-09-15',
    listingDate: '2026-09-17',
    tentativeDates: [],
    priceBandLow: 322,
    priceBandHigh: 339,
    lotSize: 44,
    issueSizeCr: 805,
    issueType: 'Book built',
    exchanges: ['NSE', 'BSE'],
    gmp: 0,
    gmpUpdated: '2026-09-14T12:30:00+05:30',
    subscription: { total: 1.42, asOf: 'Final' },
    about:
      '₹805 Cr issue from the Manipal group’s payment card and identity solutions business. The book closed at 1.42x and the grey market quote is flat to marginally negative.',
    sourceName: 'IPO Ji',
    sourceUrl: 'https://www.ipoji.com/ipo/manipal-payment-and-identity-ipo',
  },
  {
    id: 'steamhouse-india',
    name: 'Steamhouse India',
    segment: 'Mainboard',
    platform: 'NSE',
    openDate: '2026-09-09',
    closeDate: '2026-09-11',
    allotmentDate: '2026-09-15',
    listingDate: '2026-09-17',
    tentativeDates: [],
    priceBandLow: 77,
    priceBandHigh: 81,
    lotSize: 185,
    issueSizeCr: 414,
    issueType: 'Book built',
    exchanges: ['NSE', 'BSE'],
    gmp: 20,
    gmpUpdated: '2026-09-14T12:30:00+05:30',
    subscription: { total: 32.07, asOf: 'Final' },
    about:
      '₹414 Cr mainboard issue priced at ₹77-81, closed 32.07x subscribed with a +₹20 grey market quote.',
    sourceName: 'IPO Ji',
    sourceUrl: 'https://www.ipoji.com/ipo/steamhouse-india-ipo',
  },
];

export const IPOT: IPO[] = IPOT_RAW;

export const IPO_BY_ID: Record<string, IPO> = IPOT.reduce((acc, ipo) => {
  acc[ipo.id] = ipo;
  return acc;
}, {} as Record<string, IPO>);

export function getIpo(id: string): IPO | undefined {
  return IPO_BY_ID[id];
}
