import { IPO } from './types';

/**
 * Curated IPO board.
 * GMP + subscription figures cross-checked against public trackers
 * (ipoji.com, ipowatch.in, ipocentral.in, ET Now, NDTV Profit, Groww blog)
 * as of 5 September 2026, 7:45 PM IST.
 */
export const DATA_AS_OF = '2026-09-05T19:45:00+05:30';
export const DATA_AS_OF_LABEL = '5 Sep 2026, 7:45 PM IST';

export const IPOT: IPO[] = [
  {
    id: 'kanohar-electricals',
    name: 'Kanohar Electricals',
    sector: 'Power Equipment',
    segment: 'Mainboard',
    openDate: '2026-09-08',
    closeDate: '2026-09-10',
    allotmentDate: '2026-09-11',
    listingDate: '2026-09-14',
    tentativeDates: ['allotment', 'listing'],
    priceBandLow: 601,
    priceBandHigh: 632,
    lotSize: 23,
    issueSizeCr: 1055.74,
    issueType: 'Book built \u2022 Fresh + OFS',
    exchanges: ['NSE', 'BSE'],
    gmp: 205,
    about:
      'Domestic transformer manufacturer and EPC solutions provider serving India\u2019s power and energy infrastructure sectors.',
    sourceName: 'IPO Ji / IPO Watch',
    sourceUrl: 'https://www.ipoji.com/ipo/kanohar-electricals-ipo',
  },
  {
    id: 'veegaland-developers',
    name: 'Veegaland Developers',
    sector: 'Real Estate',
    segment: 'Mainboard',
    openDate: '2026-09-10',
    closeDate: '2026-09-15',
    allotmentDate: '2026-09-16',
    listingDate: '2026-09-18',
    tentativeDates: ['allotment', 'listing'],
    priceBandLow: 130,
    priceBandHigh: 140,
    lotSize: 107,
    issueType: 'Book built',
    exchanges: ['NSE', 'BSE'],
    gmp: 22,
    about:
      'Kerala-based real estate developer focused on residential apartment projects across southern India.',
    sourceName: 'IPORise',
    sourceUrl: 'https://www.iporise.com/ipo/veegaland-developers-ipo',
  },
  {
    id: 'ashutosh-fibre',
    name: 'Ashutosh Fibre',
    sector: 'Textiles & Fibres',
    segment: 'SME',
    openDate: '2026-08-31',
    closeDate: '2026-09-02',
    allotmentDate: '2026-09-04',
    listingDate: '2026-09-07',
    tentativeDates: [],
    priceBandLow: 87,
    priceBandHigh: 92,
    lotSize: 1200,
    issueSizeCr: 56.35,
    issueType: 'Book built \u2022 Fresh issue',
    exchanges: ['NSE SME'],
    gmp: 35,
    about:
      'Manufacturer of polyester and blended fibre products, raising \u20B956.35 Cr entirely through a fresh issue of 61.25 lakh shares.',
    sourceName: 'Goodreturns / IPO Watch',
    sourceUrl: 'https://ipowatch.in/ashutosh-fibre-ipo/',
  },
  {
    id: 'esds-software',
    name: 'ESDS Software Solution',
    sector: 'IT Services & Cloud',
    segment: 'Mainboard',
    openDate: '2026-08-28',
    closeDate: '2026-09-01',
    allotmentDate: '2026-09-02',
    listingDate: '2026-09-04',
    tentativeDates: ['listing'],
    priceBandLow: 404,
    priceBandHigh: 426,
    lotSize: 35,
    issueType: 'Book built',
    exchanges: ['NSE', 'BSE'],
    gmp: 247,
    subscription: {
      qib: 39.87,
      nii: 166.49,
      retail: 106.76,
      asOf: 'Close of day 3',
    },
    about:
      'Cloud, data-centre and cyber-security services provider (Nashik) \u2014 one of the most heavily subscribed issues of the season.',
    sourceName: 'Economic Times / Groww',
    sourceUrl: 'https://groww.in/blog/esds-software-solution-ipo-day-3-subscription-status',
  },
  {
    id: 'deepa-jewellers',
    name: 'Deepa Jewellers',
    sector: 'Jewellery Retail',
    segment: 'Mainboard',
    openDate: '2026-09-01',
    closeDate: '2026-09-03',
    allotmentDate: '2026-09-07',
    listingDate: '2026-09-09',
    tentativeDates: ['allotment', 'listing'],
    priceBandLow: 168,
    priceBandHigh: 177,
    lotSize: 84,
    issueType: 'Book built',
    exchanges: ['NSE', 'BSE'],
    gmp: 22,
    subscription: { retail: 4.85, total: 3.69, asOf: 'Close of day 2' },
    about:
      'Retail jewellery chain priced at \u20B9168\u2013\u20B9177 per share, with a minimum application of about \u20B914,868 per lot of 84 shares.',
    sourceName: 'Univest / ET Now',
    sourceUrl:
      'https://univest.in/blogs/deepa-jewellers-initial-public-offering-day-3-subscription-3-september-2026',
  },
  {
    id: 'priority-jewels',
    name: 'Priority Jewels',
    sector: 'Jewellery Manufacturing',
    segment: 'Mainboard',
    openDate: '2026-08-28',
    closeDate: '2026-09-01',
    allotmentDate: '2026-09-02',
    listingDate: '2026-09-04',
    tentativeDates: ['listing'],
    lotSize: 75,
    issueType: 'Book built',
    exchanges: ['NSE', 'BSE'],
    gmp: 28,
    about:
      'Jewellery manufacturer and exporter. Applications ranged from \u20B915,000 (min) to \u20B91,95,000 (max) per investor.',
    sourceName: 'm.Stock',
    sourceUrl: 'https://www.mstock.com/ipo/priority-jewels-ltd/ipo677',
  },
  {
    id: 'nse-limited',
    name: 'NSE (National Stock Exchange)',
    sector: 'Capital Markets',
    segment: 'Mainboard',
    openDate: '2026-10-05',
    closeDate: '2026-10-07',
    allotmentDate: '2026-10-09',
    listingDate: '2026-10-13',
    tentativeDates: ['open', 'close', 'allotment', 'listing'],
    exchanges: ['NSE', 'BSE'],
    gmp: 285,
    about:
      'India\u2019s largest exchange by traded value. The long-pending share sale is awaiting final regulatory clearance \u2014 dates and price band are indicative.',
    sourceName: 'IPO Watch',
    sourceUrl: 'https://ipowatch.in/upcoming-ipo-list/',
  },
  {
    id: 'prasol-chemicals',
    name: 'Prasol Chemicals',
    sector: 'Specialty Chemicals',
    segment: 'Mainboard',
    openDate: '2026-09-09',
    closeDate: '2026-09-11',
    allotmentDate: '2026-09-14',
    listingDate: '2026-09-16',
    tentativeDates: ['open', 'close', 'allotment', 'listing'],
    exchanges: ['NSE', 'BSE'],
    gmp: 170,
    about:
      'Specialty chemicals manufacturer serving pharma, agro and industrial end-markets. Price band and issue size await the RHP.',
    sourceName: 'IPO Watch',
    sourceUrl: 'https://ipowatch.in/upcoming-ipo-list/',
  },
  {
    id: 'rentomojo',
    name: 'Rentomojo',
    sector: 'Consumer Rentals',
    segment: 'Mainboard',
    openDate: '2026-09-09',
    closeDate: '2026-09-11',
    allotmentDate: '2026-09-14',
    listingDate: '2026-09-16',
    tentativeDates: ['open', 'close', 'allotment', 'listing'],
    exchanges: ['NSE', 'BSE'],
    gmp: 95,
    about:
      'Furniture and appliance rental marketplace operating across major Indian cities. Among 11 mainboard issues expected next week.',
    sourceName: 'NDTV Profit / IPO Watch',
    sourceUrl:
      'https://www.ndtvprofit.com/markets/upcoming-ipos-next-week-rentomojo-pranav-constructions-kanohar-electricals-among-11-mainboard-issues-to-launch-next-week-12001813',
  },
  {
    id: 'glass-wall-systems',
    name: 'Glass Wall Systems',
    sector: 'Building Materials',
    segment: 'Mainboard',
    openDate: '2026-09-14',
    closeDate: '2026-09-16',
    allotmentDate: '2026-09-18',
    listingDate: '2026-09-21',
    tentativeDates: ['open', 'close', 'allotment', 'listing'],
    exchanges: ['NSE', 'BSE'],
    gmp: 65,
    about:
      'Architectural glazing and aluminium facade systems supplier to commercial real estate projects.',
    sourceName: 'IPO Watch',
    sourceUrl: 'https://ipowatch.in/upcoming-ipo-list/',
  },
  {
    id: 'pranav-constructions',
    name: 'Pranav Constructions',
    sector: 'Infrastructure',
    segment: 'SME',
    openDate: '2026-09-09',
    closeDate: '2026-09-11',
    allotmentDate: '2026-09-14',
    listingDate: '2026-09-16',
    tentativeDates: ['open', 'close', 'allotment', 'listing'],
    exchanges: ['BSE SME'],
    gmp: 37,
    about:
      'Civil construction and real-estate development company. One of the mainboard/SME issues lined up for the coming week.',
    sourceName: 'NDTV Profit / IPO Watch',
    sourceUrl: 'https://ipowatch.in/upcoming-ipo-list/',
  },
  {
    id: 'karamtara-engineering',
    name: 'Karamtara Engineering',
    sector: 'Solar Structures',
    segment: 'SME',
    openDate: '2026-09-14',
    closeDate: '2026-09-16',
    allotmentDate: '2026-09-18',
    listingDate: '2026-09-21',
    tentativeDates: ['open', 'close', 'allotment', 'listing'],
    exchanges: ['NSE SME'],
    gmp: 40,
    about:
      'Manufacturer of solar module mounting structures and galvanised steel products for the renewable energy industry.',
    sourceName: 'IPO Watch',
    sourceUrl: 'https://ipowatch.in/upcoming-ipo-list/',
  },
  {
    id: 'manipal-payment',
    name: 'Manipal Payment Solutions',
    sector: 'Fintech & Payments',
    segment: 'Mainboard',
    openDate: '2026-09-16',
    closeDate: '2026-09-18',
    allotmentDate: '2026-09-21',
    listingDate: '2026-09-23',
    tentativeDates: ['open', 'close', 'allotment', 'listing'],
    exchanges: ['NSE', 'BSE'],
    gmp: 30,
    about:
      'Payment cards, banking technology and transaction-processing business of the Manipal group.',
    sourceName: 'IPO Watch',
    sourceUrl: 'https://ipowatch.in/upcoming-ipo-list/',
  },
  {
    id: 'lcc-projects',
    name: 'LCC Projects',
    sector: 'Civil Infrastructure',
    segment: 'SME',
    openDate: '2026-09-15',
    closeDate: '2026-09-17',
    allotmentDate: '2026-09-21',
    listingDate: '2026-09-23',
    tentativeDates: ['open', 'close', 'allotment', 'listing'],
    exchanges: ['NSE SME'],
    gmp: 17,
    about: 'Civil works and infrastructure contractor. Key terms will be disclosed in the RHP.',
    sourceName: 'IPO Watch',
    sourceUrl: 'https://ipowatch.in/upcoming-ipo-list/',
  },
  {
    id: 'steamhouse-india',
    name: 'Steamhouse India',
    sector: 'Consumer',
    segment: 'SME',
    openDate: '2026-09-17',
    closeDate: '2026-09-19',
    allotmentDate: '2026-09-21',
    listingDate: '2026-09-24',
    tentativeDates: ['open', 'close', 'allotment', 'listing'],
    exchanges: ['BSE SME'],
    gmp: 0,
    about: 'SME issue with no premium recorded in the grey market. Awaiting RHP for issue details.',
    sourceName: 'IPO Watch',
    sourceUrl: 'https://ipowatch.in/upcoming-ipo-list/',
  },
  {
    id: 'asset-reconstruction',
    name: 'Asset Reconstruction Co.',
    sector: 'Stressed Assets',
    segment: 'Mainboard',
    openDate: '2026-09-21',
    closeDate: '2026-09-23',
    allotmentDate: '2026-09-25',
    listingDate: '2026-09-29',
    tentativeDates: ['open', 'close', 'allotment', 'listing'],
    exchanges: ['NSE', 'BSE'],
    gmp: 0,
    about:
      'Asset reconstruction company focused on acquisition and resolution of stressed financial assets.',
    sourceName: 'IPO Watch',
    sourceUrl: 'https://ipowatch.in/upcoming-ipo-list/',
  },
  {
    id: 'rays-of-belief',
    name: 'Rays of Belief',
    sector: 'Renewable Energy',
    segment: 'SME',
    openDate: '2026-09-22',
    closeDate: '2026-09-24',
    allotmentDate: '2026-09-28',
    listingDate: '2026-09-30',
    tentativeDates: ['open', 'close', 'allotment', 'listing'],
    exchanges: ['BSE SME'],
    gmp: 12,
    about: 'Renewable energy EPC player. Grey market premium has softened over the last few sessions.',
    sourceName: 'IPO Watch',
    sourceUrl: 'https://ipowatch.in/upcoming-ipo-list/',
  },
  {
    id: 'purple-style-labs',
    name: 'Purple Style Labs (Purplle)',
    sector: 'E-commerce',
    segment: 'Mainboard',
    openDate: '2026-09-28',
    closeDate: '2026-09-30',
    allotmentDate: '2026-10-02',
    listingDate: '2026-10-06',
    tentativeDates: ['open', 'close', 'allotment', 'listing'],
    exchanges: ['NSE', 'BSE'],
    gmp: 2,
    about:
      'Owner of the Purplle beauty and personal-care marketplace. Grey market sentiment is currently flat.',
    sourceName: 'IPO Watch',
    sourceUrl: 'https://ipowatch.in/upcoming-ipo-list/',
  },
];

export const IPO_BY_ID: Record<string, IPO> = IPOT.reduce((acc, ipo) => {
  acc[ipo.id] = ipo;
  return acc;
}, {} as Record<string, IPO>);

export function getIpo(id: string): IPO | undefined {
  return IPO_BY_ID[id];
}
